# Generated by Django 5.2.10 on 2026-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
