# Generated by Django 5.2.10 on 2026-03-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_greeting',
            field=models.BooleanField(default=False),
        ),
    ]
